{{- range .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $.namespace }}
type: Opaque
data:
  {{- range $key, $value := .data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: pre-install-agent-secret-check
  annotations:
    "helm.sh/hook": pre-install
spec:
  template:
    spec:
      containers:
      - name: check-agent-secret
        image: finalgene/openssh:9
        command: ["openssl"]
        args: ["rand", "-hex", "32"]
      restartPolicy: OnFailure
